### ISSUE TITLE
kwu09 Kv channel init_state error

### ISSUE THREAD

**Issue by kyralianaka** [jaxleyverse/jaxley-mech#44]
I get the error `TypeError: Kv.init_state() missing 2 required positional arguments: 'params' and 'delta_t'` when trying to call init_state() on a cell with the kwu09.Kv channel @huangziwei

**Comment by huangziwei** [comment]
have you tried pulling the latest `jaxley` and `jaxley-mech`?  Both should be >=0.2.0

**Comment by kyralianaka** [comment]
Ahh that fixes it thanks!
